# Generated by Django 4.1.7 on 2023-09-14 09:28

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=800)),
                ('category', models.CharField(choices=[('car', 'car'), ('motorcycle', 'motorcycle'), ('scooters', 'scooters')], default='car', max_length=10)),
                ('img', models.ImageField(upload_to=app.models.upload_to)),
                ('startingPrice', models.FloatField()),
                ('startAuction', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(blank=True, default=60)),
                ('endAuction', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=6)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('txId', models.CharField(blank=True, default=None, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/users/default_profile.jpg', upload_to=app.models.upload_profile_pics)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lot')},
            },
        ),
    ]
